import { GoogleGenAI, Type } from '@google/genai';
import { ThemeData, PuzzleMechanic } from '../models/PuzzleData';

// Placeholder for API key, in a real app this should be securely managed
const apiKey = (import.meta as any).env ? (import.meta as any).env.VITE_GEMINI_API_KEY : 'MISSING_API_KEY';
const ai = new GoogleGenAI({ apiKey: apiKey || 'MISSING_API_KEY' });

export class ThemeGenerator {
  
  /**
   * Translates abstract pure math logic into a thematic narrative puzzle using Gemini.
   */
  static async generateSkin(mechanic: PuzzleMechanic, abstractLogic: any): Promise<ThemeData> {
    if (apiKey === 'MISSING_API_KEY') {
      console.warn("No Gemini API key provided. Falling back to static mock skin.");
      return this.getMockSkin(mechanic, abstractLogic);
    }

    try {
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: [
          { role: 'user', parts: [{ text: this.buildPrompt(mechanic, abstractLogic) }] }
        ],
        config: {
          responseMimeType: 'application/json',
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              skin_id: { type: Type.STRING, description: "A unique snake_case ID for this theme" },
              title: { type: Type.STRING, description: "A catchy, Professor Layton style title" },
              narrative_setup: { type: Type.STRING, description: "A highly creative 1-2 sentence story setup" },
              rules_description: { type: Type.STRING, description: "The constraints translated into the story's logic" },
              entity_map: { 
                type: Type.OBJECT,
                description: "Map abstract entity IDs (e.g. E_A, E_B) to thematic names (e.g. 'Knight', 'Dragon')"
              }
            },
            required: ["skin_id", "title", "narrative_setup", "rules_description", "entity_map"]
          }
        }
      });

      const jsonStr = response.text || '{}';
      const parsed = JSON.parse(jsonStr);

      // In the real implementation, we would also generate images dynamically or map to existing banks.
      // For this demo, we mock the asset URLs based on the generated entity mapping.
      const sprites = Object.keys(parsed.entity_map).map(logicId => ({
        id: logicId,
        url: `/assets/mock/${parsed.skin_id}_${logicId}.png`
      }));

      return {
        ...parsed,
        assets: {
          sprites
        }
      };
    } catch (e) {
      console.error("Gemini Theme Generation failed:", e);
      return this.getMockSkin(mechanic, abstractLogic);
    }
  }

  private static buildPrompt(mechanic: PuzzleMechanic, logic: any): string {
    return `
You are a creative puzzle writer for a game like Professor Layton.
I have a pure math logic puzzle generated by my engine.
Mechanic: ${mechanic}
Abstract Logic JSON: ${JSON.stringify(logic)}

Your job is to invent a HIGHLY CREATIVE, UNIQUE, and UNEXPECTED theme for this logic.
Do not use the standard cliché themes (e.g., if it's constraint_transfer, DO NOT use wolves/sheep/cabbage or missionaries/cannibals).
Instead, use something wild like:
- Astronauts moving alien specimens
- A spy transferring radioactive briefcases
- A chef mixing volatile ingredients

Map EVERY abstract entity (e.g. E_A, E_B) to a specific noun in your theme.
Keep the narrative short and witty.
Output strictly JSON.
    `;
  }

  private static getMockSkin(mechanic: PuzzleMechanic, logic: any): ThemeData {
    // Fallback if AI fails or no API key is present
    return {
      skin_id: 'mock_elevator_overload',
      title: '超载的电梯 (Fallback)',
      narrative_setup: '大厦即将关门，保安大叔必须把所有奇怪的展品运回顶楼。',
      rules_description: '电梯每次只能装两样东西，且必须有人操作。注意，猫不能和古董花瓶单独留下，狗不能和猫单独留下！',
      entity_map: {
        'E_A': '保安大叔',
        'E_B': '大黄狗',
        'E_C': '暹罗猫',
        'E_D': '古董花瓶'
      },
      assets: {
        sprites: [
          { id: 'E_A', url: '/assets/mock/guard.png' },
          { id: 'E_B', url: '/assets/mock/dog.png' },
          { id: 'E_C', url: '/assets/mock/cat.png' },
          { id: 'E_D', url: '/assets/mock/vase.png' }
        ]
      }
    };
  }
}
